// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuxZi4tXcreGVkMZc8PoYLjgAWtSjf4qU',
    appId: '1:327330284001:web:e05996acb80a45c4ea92a0',
    messagingSenderId: '327330284001',
    projectId: 'topread',
    authDomain: 'topread.firebaseapp.com',
    storageBucket: 'topread.firebasestorage.app',
    measurementId: 'G-GPXNDTEJQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdSZecWObdiRRHvFtu9_Zw1oQWy_ilps',
    appId: '1:327330284001:android:9e3bc121128c22fcea92a0',
    messagingSenderId: '327330284001',
    projectId: 'topread',
    storageBucket: 'topread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58i366GQ74ov0NW7543iMi0gWRlwpEGw',
    appId: '1:327330284001:ios:c6c3834481f01681ea92a0',
    messagingSenderId: '327330284001',
    projectId: 'topread',
    storageBucket: 'topread.firebasestorage.app',
    iosBundleId: 'com.topread.novel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58i366GQ74ov0NW7543iMi0gWRlwpEGw',
    appId: '1:327330284001:ios:890de454a96a7a49ea92a0',
    messagingSenderId: '327330284001',
    projectId: 'topread',
    storageBucket: 'topread.firebasestorage.app',
    iosBundleId: 'com.novel.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuxZi4tXcreGVkMZc8PoYLjgAWtSjf4qU',
    appId: '1:327330284001:web:d6bbaa9b34e434ebea92a0',
    messagingSenderId: '327330284001',
    projectId: 'topread',
    authDomain: 'topread.firebaseapp.com',
    storageBucket: 'topread.firebasestorage.app',
    measurementId: 'G-DJKC0GGYCE',
  );
}
